# Generated by Django 3.1.14 on 2022-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portal1',
            fields=[
                ('rollno', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('invoiceno', models.IntegerField()),
                ('indentno', models.IntegerField()),
                ('bill', models.FileField(upload_to='uploads/')),
                ('billID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
